networks:
  cameras-net:
    driver: bridge

services:
  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    restart: unless-stopped
    ports:
      - "1984:1984"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml:ro
      - ./cameras.json:/config/cameras.json:ro
    networks:
      - cameras-net
      
  web:
    build:
      context: ./web
      args:
        - VITE_GO2RTC_PORT=${VITE_GO2RTC_PORT}
        - VITE_PUBLISH_IN=${VITE_PUBLISH_IN}
      container_name: painel_cameras_web
      restart: unless-stopped
      ports:
        - "${WEB_PORT}:80"
      volumes:
        - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
        - ./cameras.json:/etc/nginx/cameras.json:ro
        - ${RECORD_PATH}:/record:ro
      depends_on:
        - go2rtc
      networks:
        - cameras-net