server {
    listen 80;
    server_name localhost;

    location = /config.json {
        default_type application/json;
        return 200 '{"go2rtcPort": "${GO2RTC_PORT}", "basePath": "${BASE_PATH}", "jsonCamera": "${JSON_CAMERA}", "placeOfExecution": "${LOCATION_RUN}"}';
        add_header Access-Control-Allow-Origin *;
    }

    location = ${BASE_PATH} {
        return 301 ${BASE_PATH}/;
    }

    location ${BASE_PATH}/ {
        alias /usr/share/nginx/html/;
        index index.html;
    }

    location = /cameras.json {
        alias /etc/nginx/cameras.json;
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
    }

    location /recordings/ {
        alias /record/;
        autoindex on;
        autoindex_format json;
        add_header Access-Control-Allow-Origin *;
    }
}