server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location = /cameras.json {
        alias /etc/nginx/cameras.json;
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
    }

    location /recordings/ {
        alias /record/;
        autoindex on;
        autoindex_format json;
        add_header Access-Control-Allow-Origin *;
    }
}